### ISSUE TITLE
Should new tags be added to "master_tags" in "scraper_main.py"?

### ISSUE THREAD

**Issue by justinwangscu** [jmaguin/daily-digest#1]
CNN has "opinions", "style" and "travel" sections. Can I add that to the master_tags list? 
For now I have commented out the tags in the Cnn data structure that are not in the master list.

What is master_tags going to be used for in the future?

**Comment by jmaguin** [comment]
Yes, if those tags (or an equivalent like nation/national/us) are not already in master_tags then add them. The point of master_tags is it is supposed to be the master list of tags we will present to the user for them to choose which they are interested in.
