### ISSUE TITLE
GPT4ALL - Discussion

### ISSUE THREAD

**Issue by justinwangscu** [jmaguin/daily-digest#3]
I tested "wizardlm-13b-v1.2.Q4_0.gguf" and asked it"What is the longest month?"

Result: 224.33 Seconds

Not good.

Post your results and other things pertaining to the topic here

**Comment by justinwangscu** [comment]
**Design Report Overleaf Link (With Edit Perms):** 
[https://www.overleaf.com/7942964685wttgwfnjzqqs#fbd408](https://www.overleaf.com/7942964685wttgwfnjzqqs#fbd408)

**Comment by jmaguin** [comment]
I've been using orca mini and mistral 7b. Asking a similar prompt to that orca responds in ~9 sec and mistral takes about twice as long. For summarizing whole articles it will probably take much longer
